spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/angularPost'
    username: Ashish
    password: welcome
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
